### ISSUE TITLE
Steps to install and contribute to this project

### ISSUE THREAD

**Issue by willianjusten** [guilouro/devent#2]
I had a lot of trouble to make the system work... Can you say what I need to do to run this project locally?

**Comment by johnidm** [comment]
Hi @willianjusten, 

Are you having problems running the project locally?

Let me know if you need any help

**Comment by willianjusten** [comment]
It's working for now, but I really appreciate a documentation =)

**Comment by guilouro** [comment]
Thanks, I'll improve
